name: Node.js Pipeline

on:
  push:
    branches:
      - main

#env:
#  SONARQUBE_URL: http://127.0.0.1:9000
#  DOCKER_USERNAME: 
#  DOCKER_PASSWORD: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install


  sonarqube:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install SonarScanner
        run: |
          curl -sL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
          sudo apt-get install -y nodejs
          sudo npm install -g sonarqube-scanner

#      - name: Run SonarScanner
#        run: |
#          sonar-scanner \
#            -Dsonar.projectKey=$GITHUB_REPOSITORY \
#            -Dsonar.sources=./ \
#            -Dsonar.host.url=$SONARQUBE_URL \
#            -Dsonar.login=$SONARQUBE_TOKEN
#
#  build-docker-image:
#    needs: sonarqube
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Build Docker image
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          push: true
#          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-app:${{ github.sha }}
#
#  deploy:
#    needs: build-docker-image
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Pull Docker image
#        uses: docker/metadata-action@v3
#        with:
#          images: ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-app:${{ github.sha }}
#      - name: Start Docker container
#        run: |
#          docker run --rm -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-app:${{ github.sha }}
#
##################
